version: "3.8"

networks:
  rede-docker:
    external: true
    driver: bridge
    name: rede-docker

services:
  mysql5:
    image: mysql:5-debian
    networks:
      - rede-docker
    container_name: mysql5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: basico
      MYSQL_USER: hlam
      MYSQL_PASSWORD: hlam
    ports:
      - "3306:3306"
    volumes:
      - ./dados:/var/lib/mysql

volumes:
  mysql5_data:
