version: '3.8'

networks:
  rede-docker:
    external: true
    driver: bridge
    name: rede-docker

services:
  app-redis:
    image: redis
    networks:
      - rede-docker
    container_name: redis
    command: redis-server --requirepass 123456789
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: basico
      MYSQL_USER: hlam
      MYSQL_PASSWORD: hlam
    ports:
      - "6379:6379"
    volumes:
      - ./dados:/data

volumes:
  redis_data: